kind: pipeline
type: ssh
name: MEP twin/skred UI

server:
  host: wp.skred.mobi
  user: drone-ci
  ssh_key:
       from_secret: private_key

steps:

  - name: remove old configuration folder
    commands:
      - sudo rm -rf /srv/call.skred.mobi.old && sudo rm -rf /srv/call.twin.me.old

  - name: start docker-compose
    commands:
      - HOME=/home/drone-ci && docker pull harbor.skyrock.net/twinlife/usine-nodejs-webapp:latest && docker compose up

  - name: Verify docker status
    commands: 
      - bash check_container_exit_code.sh

  - name: remove docker container
    commands:
      - docker rm usine-webapp-twinlife

  - name: Backup old folder
    commands: 
      - sudo mv /srv/call.skred.mobi/* /srv/call.skred.mobi.old && sudo mv /srv/call.twin.me/* /srv/call.twin.me.old

  - name: MEP
    commands: 
      - sudo mv skred-webapp-ui/* /srv/call.skred.mobi/ && sudo chown -R 1000:1000 /srv/call.skred.mobi && sudo mv twinme-webapp-ui/* /srv/call.twin.me/ && sudo chown -R 1000:1000 /srv/call.twin.me

trigger:
  event:
  - tag
  #branch:
  #- master
