kind: pipeline
type: docker
name: CALL/TRANSFER - MEP twin/skred webapp UI

workspace:
  path: /opt/usine

clone:
  disable: true
  
steps:
     - name: CALL/TRANSFER - clone
       image: harbor.prodin.orbus.fr/usine-mep/usine-nodejs:latest
       environment:
          GIT_USERNAME:
            from_secret: drone_git_username
          GIT_PASSWORD:
            from_secret: drone_git_password
          DRONE_COMMIT: $DRONE_COMMIT
       commands:
       - cd /opt/usine
       - echo $GIT_USERNAME
       - git clone https://$GIT_USERNAME:$GIT_PASSWORD@gogs.skyrock.net/TwinMe/server-webapp-ui.git .
       - git checkout $DRONE_COMMIT

     - name: CALL/TRANSFER - NPM install typescript and npm audit
       image: harbor.prodin.orbus.fr/usine-mep/usine-nodejs:latest
       user: drone-ci
       commands:
       - cd /opt/usine
       - npm install typescript && npm audit --audit-level=critical

     - name: CALL - Build web UI
       image: harbor.prodin.orbus.fr/usine-mep/usine-nodejs:latest
       user: drone-ci
       commands:
       - cd /opt/usine
       - npm run build:skred && npm run build:twinme

     - name: TRANSFER - Build web transfer UI
       image: harbor.prodin.orbus.fr/usine-mep/usine-nodejs:latest
       user: drone-ci
       commands:
       - cd /opt/usine
       - npm run build:skred:transfer && npm run build:twinme:transfer

     - name: CALL/TRANSFER - MEP web UI
       image: harbor.prodin.orbus.fr/skyrock/drone-mep:latest
       user: drone-ci
       commands:
       - /bin/bash /home/drone-ci/mep-twinlife-webapp-ui-webapp.sh webapp24.skred.mobi

image_pull_secrets:
- harborsecret

trigger:
  event:
  - tag
  ref:
      include:
        - refs/tags/webapp-*

---
kind: pipeline
type: docker
name: MEET - MEP twin/skred webapp UI

workspace:
  path: /opt/usine

clone:
  disable: true
  
steps:
     - name: MEET - clone
       image: harbor.prodin.orbus.fr/usine-mep/usine-nodejs:latest
       environment:
          GIT_USERNAME:
            from_secret: drone_git_username
          GIT_PASSWORD:
            from_secret: drone_git_password
          DRONE_COMMIT: $DRONE_COMMIT
       commands:
       - cd /opt/usine
       - echo $GIT_USERNAME
       - git clone https://$GIT_USERNAME:$GIT_PASSWORD@gogs.skyrock.net/TwinMe/server-webapp-ui.git .
       - git checkout $DRONE_COMMIT

     - name: MEET - NPM install typescript and npm audit
       image: harbor.prodin.orbus.fr/usine-mep/usine-nodejs:latest
       user: drone-ci
       commands:
       - cd /opt/usine
       - npm install typescript && npm audit --audit-level=critical
       
     - name: MEET - Build web UI
       image: harbor.prodin.orbus.fr/usine-mep/usine-nodejs:latest
       user: drone-ci
       commands:
       - cd /opt/usine
       - npm run build:skred:meet && npm run build:twinme:meet

     - name: MEET - MEP web UI
       image: harbor.prodin.orbus.fr/skyrock/drone-mep:latest
       user: drone-ci
       commands:
       - /bin/bash /home/drone-ci/mep-twinlife-webapp-ui-meet.sh webapp24.skred.mobi

image_pull_secrets:
- harborsecret

trigger:
  event:
  - tag
  ref:
      include:
        - refs/tags/meet-*