services:
    usine-webapp-twinlife:
        volumes:
            - '.:/opt/nodejs'
        entrypoint: /bin/bash
        command: "-c 'npm install typescript && npm audit --audit-level=critical && npm run build:skred && npm run build:twinme && npm run build:skred:transfer && npm run build:twinme:transfer'"
        container_name: usine-webapp-twinlife
        image: 'harbor.skyrock.net/twinlife/usine-nodejs-webapp:22'